### ISSUE TITLE
renamed files

### ISSUE THREAD

**Issue by sjanssen2** [wasade/q2-fragment-insertion#5]
https://github.com/wasade/q2-fragment-insertion/blob/64d4b52847fef856ebcf01c6459395af0dcb5c7f/q2_fragment_insertion/_insertion.py#L50

Is there a reason why you chose to not use the tree and placement files (.relabelled) that have the restored internal node labels? As far as I understand the code, Siavash assigns every node a unique ID and prefixed the original label with this ID. In a postprocessing step (a generated python program) those IDs get trimmed from the labels to restore their original values.
Thus, users don't see those IDs in e.g. the taxonomy labels of the reference.

**Comment by wasade** [comment]
No strong feelings. Present tree is not great for taxonomy

**Comment by sjanssen2** [comment]
true, but I think more useful for end users than the non-renamed

**Comment by wasade** [comment]
Okay, sounds good. Okay with changing

**Comment by sjanssen2** [comment]
Now returning the renamed tree: PR #7
