### ISSUE TITLE
reference as input or parameter

### ISSUE THREAD

**Issue by sjanssen2** [wasade/q2-fragment-insertion#6]
Hi @wasade ,
testing is currently not very convenient, because of the long waiting times. Therefore, I think passing reference tree/alignment would be quite beneficial. I wonder how to design that.

Since both are Semantic Types (FeatureData[AlignedSequence] Phylogeny[Rooted]) they can only be "inputs" not "parameters" right? If so, do you know if it is possible to have optional inputs?

If not, the user needs to always pass reference alignment and reference phylogeny as q2 artifacts. Do we really want to put that burden to users or would we be fine to have two "parameters" (which can be optional) that point to filenames?

P.S. could you invite me to the slack channel for q2?

**Comment by wasade** [comment]
Sounds good. Unsure about optional inputs but I think not. What about instead of optional inputs, a method for establishing a reference which uses the types you propose, and a method which can take a reference that has been established?

**Comment by sjanssen2** [comment]
Greg says that optional inputs are possible: 

gregcaporaso: @Stefan, yes - see the `phylogeny` input here: https://github.com/qiime2/q2-diversity/blob/master/q2_diversity/_alpha/_visualizer.py#L266

I am building that in at the moment. I think that is easier than coming up with a new Semantic type of a "Reference"

**Comment by sjanssen2** [comment]
Now implemented as optional inputs in PR #7
